### ISSUE TITLE
Not reading in a link(?)

### ISSUE THREAD

**Issue by azade-k** [joshy/striprtf#10]
Hi,

I have roughly 2000 rtf files containing articles and I realized that it does not read in the title which is formatted in blue and underlined (like a link but I cannot find an actual link behind it). If I manually set the title to "normal" formatting, it does read it in though. Do you have an idea where that might come from?

Thanks for your help!

**Comment by joshy** [comment]
Hi,

if you can provide a sample rtf file I can check.

Best regards,
Joshy

--

**Comment by azade-k** [comment]
Hi,

since they are news articles, the copyright restricts me from attaching one of the files. I am trying to replicate the problem to a test file without actual data. 

Best
Azade

**Comment by azade-k** [comment]
I created a sample file [example.zip](https://github.com/joshy/striprtf/files/4730351/example.zip)

Also, here is the code I use: 

`#script to transform rtf into txt
#imports (might need to use pip install first)
import glob
from striprtf.striprtf import rtf_to_text

# replace following line with location of your .docx file
inputfiles = 'example/*.rtf'

#listing all rtf files in the directory
input_list = sorted(glob.glob(inputfiles))
#loading and converting
for file in input_list:
    f = open(file).read()
    rtfastext = rtf_to_text(f) 
    output= file.replace('.rtf', '.txt')
    with open(output, "w") as text_file:
        print(rtfastext, file=text_file)`

I checked again and there actually is a hyperlink in the text. The code works with files without hyperlinks but not with them.

**Comment by joshy** [comment]
Hi Azade,

it seems the links are completely removed as they are inside a block which is ignored. I need to check the effort to implement a solution. 

Best,
Joshy

**Comment by joshy** [comment]
It is trickier than expected...

**Comment by carlafdzzz** [comment]
hey, could you solve the issue with hyperlink? It happens to me as well, the first line which contains the link is completely removed.

**Comment by joshy** [comment]
There is some progress on this task, see branch [hyperlinks](https://github.com/joshy/striprtf/tree/hyperlinks). The idea was to extract the link destination and the link text with a separate regex pattern. That seems to work for some example but not the one provided by @azade-k.

**Comment by HaddadJoe** [comment]
hey @joshy thanks for your work! Gave your branch a quick spin with this example. It worked fine, any updates on the release dates or ideas on how we can help?

[HyperlinksTableTest.rtf.zip](https://github.com/joshy/striprtf/files/6085265/HyperlinksTableTest.rtf.zip)

**Comment by joshy** [comment]
hey @HaddadJoe thanks for checking it out. The main problem is to find a regex pattern for hyperlinks that works across all different examples. This is the regex pattern in the [hyperlinks](https://github.com/joshy/striprtf/tree/hyperlinks) branch:
```python
HYPERLINKS = re.compile(
    r"(\{\\field\{\n?\\\*\\fldinst\{.*HYPERLINK\s(\".*\")\}{2}\s?\{.*\s+(.*)\}{2})",
    re.IGNORECASE
```

If you have time and energy you can use some online regex tester (e.g. https://regex101.com, make sure you set flavor to python) and test the pattern with the rtf files and find out if it works. That could be one way to help. 

Other ideas to tackle hyperlinks are also welcome.

**Comment by Arzemn** [comment]
I think i ran into the same issue, @joshy would it be possible to just try and capture the text in the {\\fldrslt Service:}} portion of the link parameter.. In my case i am not interested in the hyperlink itself, but the text link is part of the text body

**Comment by joshy** [comment]
@carlafdzzz @HaddadJoe @Arzemn If I have time I will look into just keeping the link description. Maybe that is easier.

**Comment by joshy** [comment]
Closed with https://github.com/joshy/striprtf/releases/tag/v0.0.21
