### ISSUE TITLE
'utf-8' codec can't decode byte 0x85 in position 14: invalid start byte

### ISSUE THREAD

**Issue by Prabakaran1410** [joshy/striprtf#25]
Hello Joshy,

I was using this library for parsing rtf file, somehow its failing to load the content.

\\par \\pard\\li180\\sb50\\f1 wow at -8,99 \\'85 so it can be profitable\\f0 \n

**Comment by joshy** [comment]
Hi Prabakaran,

could you post the full rtf? Otherwise it will be difficult to debug.

Best regard,
Joshy
