### ISSUE TITLE
striprtf parser not working for one of the rtf file

### ISSUE THREAD

**Issue by Prabakaran1410** [joshy/striprtf#26]
Adding part of the content here.

ffffffffffffffffffffffffffffffff52006f006f007400200045006e00740072007900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016000500ffffffffffffffffffffffff0c6ad98892f1d411a65f0040963251e50000000000000000000000007034
108e75dcd701feffffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffffffffffffffffffff00000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffffffffffffffffffff0000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffffffffffffffffffff000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000105000000000000

**Comment by joshy** [comment]
Hi Prabakaran,

could you post the full rtf? Otherwise it will be difficult to debug.

Thanks,
Joshy

**Comment by Prabakaran1410** [comment]
[Gardner.zip](https://github.com/joshy/striprtf/files/7582499/Gardner.zip)

**Comment by Prabakaran1410** [comment]
Can you please check with above attached file?

**Comment by joshy** [comment]
It works wit the latest version, therefore closing this issue.
