### ISSUE TITLE
cyrillic turned into chinese

### ISSUE THREAD

**Issue by bobert13** [joshy/striprtf#29]
Hi

I have 2 files in cyrillic. I can read both without issue in MS Word.
The first seems to work fine with:

```
with open(fullpath) as infile:
                content = infile.read()
                text = rtf_to_text(content ,'ignore')
```

The second (bad.zip) gets turned into chinese characters

[good.zip](https://github.com/joshy/striprtf/files/7814670/good.zip)
[bad.zip](https://github.com/joshy/striprtf/files/7814671/bad.zip)

sample output from the good one:
```
>>> tabtext =text.split("|||")
>>> print(tabtext[0])
Таблиця розподілу номерного ресурсу
Кіровоградська область|
Код зони - 52
```

sample output from the bad one:
```
>>> tabtext =text.split("|")
>>> print(tabtext[0])
亦犭桷 痤顼钿畴 眍戾痦钽 疱耋瘃
它獬怦赅 钺豚耱鼃
暑 珙龛 - 32
```

if i leave out the "ignore", i get:
**UnicodeDecodeError: 'gbk' codec can't decode byte 0xff in position 6: illegal multibyte sequence**

any idea how i can work around this?

**Comment by bobert13** [comment]
Hi,

I apologize in advance for my ignorance here. I'm pretty new to python.
Based on this email, I'm assuming you put in a commit to fix whatever
caused this issue.
Can I upgrade my current version of striprtf using pip in order to get the
fix to work?

Thanks

**Comment by joshy** [comment]
Hi, 

yes the issue is fixed but until now there was no new version. Now you can upgrade you striprtf version (0.0.19) and it should work.

BR Joshy

**Comment by bobert13** [comment]
Awesome, thanks!
