### ISSUE TITLE
Error while decoding characters

### ISSUE THREAD

**Issue by ffreller** [joshy/striprtf#30]
I'm having issues while decoding some characters.
I get the following errors when decoding some rtf text:
"'charmap' codec can't encode character '\\x96' in position 0: character maps to <undefined>",
 "'charmap' codec can't encode character '\\x93' in position 0: character maps to <undefined>",
 "'charmap' codec can't encode character '\\uf02d' in position 0: character maps to <undefined>",
 "'charmap' codec can't encode character '\\x99' in position 0: character maps to <undefined>",
 "'charmap' codec can't encode character '\\u25a1' in position 0: character maps to <undefined>",
 "'charmap' codec can't encode character '\\u2234' in position 0: character maps to <undefined>",
 "'charmap' codec can't encode character '\\x95' in position 0: character maps to <undefined>"

If necessary, I can send you the rtf files that resulted in those errors.

Thank you

**Comment by JulianSMoore** [comment]
@ffreller I have had similar issues and worked around most by opening the source file in binary mode and explicitly decoding it as utf-8 separately, then processing each line in turn rather than the whole file at once

```
with open(fOpenPath, 'rb') as rtfFile:
    rawFileContent = rtfFile.read()
    rawFileContent = rawFileContent.decode("utf-8")
    for line in rawFileContent.splitlines():
        fileContent += rtf_to_text(line, errors='backslashreplace')
```
No guarantees, but HTH

**Comment by joshy** [comment]
HI @ffreller, did you found a solution that works for you? Otherwise you can sent me the rtf files and I can have a look at it.

**Comment by ffreller** [comment]
Yes, I believe I ended up finding a workaround. Thanks!

Em dom., 5 de fev. de 2023 às 17:13, Joshy Cyriac ***@***.***>
escreveu:
