### ISSUE TITLE
Too much print with new 0.0.19

### ISSUE THREAD

**Issue by TommasoBendinelli** [joshy/striprtf#31]
Hi, Thank you for your excellent work. 
With your latest commit, there is too much printing going on (due to line 150 of striprtf.py). Ideally, it would be great to implement a logging mechanism that prints this type of information in debug mode.

**Comment by AidanHarveyNelson** [comment]
Agreed it would be good if these print statements were changed to LOG at debug level. I am running this through a lambda and it has started polluting the logs.
