### ISSUE TITLE
Some Text Being Missed {\fldrslt Service:}}

### ISSUE THREAD

**Issue by Arzemn** [joshy/striprtf#32]
I wanted to reach out to get some ideas on how best to update the code to handle a situation i have run into

I have an RTF that is encoded with text that looks like this

{\\fldrslt Service:}}

currently the striprtf is not catching this and the text 'Service:' is lost

i am looking at adding some updates to try and handle this situation and since i just started down this path looking for a little guidance

**Comment by akBeater** [comment]
@Arzemn 
I have the same problem. In my case there are email-addresses save under this "tag".
I found a workaround but I don't know which impact that change has.

from striprtf.py I removed in the list 'destinations' the words 'fldrslt' and 'field'.

In my case it worked but I don't know if I broke something else ;)

**Comment by amirali1690** [comment]
@Arzemn 
I had the same problem and @akBeater solution helped to solve the issue. Till now i haven't seen any problem

**Comment by joshy** [comment]
Thanks for helping out. Issue is now closed with https://github.com/joshy/striprtf/releases/tag/v0.0.21.
