### ISSUE TITLE
Problem importing tables

### ISSUE THREAD

**Issue by ryanthompson591** [joshy/striprtf#38]
To replicate this issue:

```
from striprtf.striprtf import rtf_to_text

RTF_TABLE = """
{\rtf1\ansi\deff0
\trowd
\cellx1000
\cellx2000
\cellx3000
\intbl cell 1\cell
\intbl cell 2\cell
\intbl cell 3\cell
\row
} 
"""

print(rtf_to_text(RTF_TABLE))
```

Expected something like:
cell 1 | cell 2 | cell 3

Actual
tf1nsi	rowdcell 1|cell 2|cell 3|ow

Note: I pulled some of the tables from [here](http://www.pindari.com/rtf3.html).

**Comment by joshy** [comment]
Hi Ryan,

I can't replicate the issue. See commit https://github.com/joshy/striprtf/commit/d4adddd0d0efd1dfc08039c008cc02c878e3c3b6. 
Closing the issue.
