### ISSUE TITLE
Fail to convert numbers sometimes

### ISSUE THREAD

**Issue by roland-gsell** [joshy/striprtf#4]
Hi,
I'm using striprtf to convert menu plans to plain text.
It works most of the time, but sometimes the date is not converted correctly.
The rtf says:
 05.08-09.08.2019 
and when I parse it, it goes like:
 05.08.-.08.2019

I'm using Python 3.7.4 and striprtf 0.0.5
It works when I use your online page (https://striprtf.dev/) - so either you fixed it there already or it has something to do with my python version.

[Speiseplan KW 32-33 Eybl.zip](https://github.com/joshy/striprtf/files/3713893/Speiseplan.KW.32-33.Eybl.zip)

UPDATE:
I tried it now with python 3.6.9 and 3.5.7 as well.
Same problem. I also have another example, where it doesn't work as well. The filename is:
Speiseplan KW 16-17 Eybl.rtf

You can find my whole project here:
https://bitbucket.org/roland-gsell/kantine

**Comment by joshy** [comment]
Hi Robert,

thanks for the report. I quickly looked at your code and it is not clear to me why you read by lines. Read the whole rtf in one go and sent it to striprtf.

With pathlib it could look like this:
```python
from pathlib import Path
from striprtf.striprtf import rtf_to_text

file_loc = Path("/where/your/file/is")
with file_loc.open() as source:
  result = rtf_to_text(source.read())
# do what you want with the result
```
Can you try this and give me feedback?

**Comment by roland-gsell** [comment]
Hi, thanks a lot.
That works just fine. Don't know why I thought I need to do that line by line.
