### ISSUE TITLE
New update error

### ISSUE THREAD

**Issue by egleidson** [joshy/striprtf#41]
Hi! cheers from Brazil.

I currently use this lib at my job, which consists of medical reports and the with the new update I was getting this error: 
'utf-8' codec can't decode byte 0xa0 in position 0: invalid start byte

And even if I used the option encoding=" " , the error still persists. 

So in order to not break the pipeline here I had to switch to the older version.

But I'm really grateful for this project couldn't do what I do without.

**Comment by joshy** [comment]
Should be fixed with version v0.0.24
