### ISSUE TITLE
pg_striprtf

### ISSUE THREAD

**Issue by raffael-mnhn** [joshy/striprtf#52]
Dear @joshy, thanks for your code. I implemented a postgresql version based on your code. You might want to reference it in your docs. You can find it at https://github.com/MnhnL/pg_striprtf . Feel free to close this issue as there is no problem with your code :)

**Comment by joshy** [comment]
Dear Raffael, wow impressive SQL. I didn't know that this was possible at all. Added a link in the readme to your script:
[e68ead6](https://github.com/joshy/striprtf/commit/e68ead6986a4312648e6126a1263167bf371b5d6)

**Comment by raffael-mnhn** [comment]
Great! Many thanks!
