### ISSUE TITLE
unmatched closing brace truncates text

### ISSUE THREAD

**Issue by crystal-butler** [joshy/striprtf#55]
I am preprocessing a variety of medical texts using `rtf_to_text`. Occasionally a text contains an unmatched closing curly brace:
"}"
These texts get cut off after the unmatched brace.

Below is an anonymized example, which gets truncated after "Judgment: Judgment normal.   }":

Chief Complaint   Patient presents with    Annual Exam         SUBJECTIVE     HISTORY OF PRESENT ILLNESS  male here today for a preventative health evaluation.    Additionally, he is following up on his hypertension.   Medication Sig Dispense Refill    fexofenadine (ALLEGRA) tablet Take 1 tablet by mouth daily as needed for allergies. fluticasone (FLONASE) nasal spray Administer 2 sprays into each nostril daily. [DISCONTINUED] tamsulosin (FLOMAX) 24 hr capsule  No current facility-administered  medications on file prior to visit.       The following portions of the patient's history were reviewed and updated as appropriate:  Tobacco | Allergies | Meds | Problems | Med Hx | Surg Hx | Fam Hx |            Health Maintenance Due   Topic Date Due    HIV Screening  Never done    Zoster Vaccines (1 of 2) Never done    Creatinine Level    Potassium Level    Sodium Level     Vitamin B12 Level      Visit: Chronic Disease, age 18+     ROS  All other systems reviewed and are negative.           OBJECTIVE      PHYSICAL EXAM  Vitals reviewed.   Constitutional       Appearance: He is well-developed.   HENT      Head: Normocephalic.      Right Ear: External ear normal.      Left Ear: External ear normal.      Nose: Nose normal.   Eyes      Pupils: Pupils are equal, round, and reactive to light.   Neck      Thyroid: No thyromegaly.   Cardiovascular      Rate and Rhythm: Normal rate and regular rhythm.      Heart sounds: Normal heart sounds.    Pulmonary       Effort: Pulmonary effort is normal.      Breath sounds: Normal breath sounds.   Abdominal      General: Bowel sounds are normal.      Palpations: Abdomen is soft.   Musculoskeletal         General: Normal range of motion.      Cervical back: Normal range of motion and neck supple.   Skin     General: Skin is warm and dry.      Capillary Refill: Capillary refill takes 2 to 3 seconds.   Neurological      Mental Status: He is alert and oriented to person, place, and time.      Deep Tendon Reflexes: Reflexes are normal and symmetric.   Psychiatric         Behavior: Behavior normal.         Thought Content: Thought content normal.         Judgment: Judgment normal.   }    ASSESSMENT / PLAN     #1 General Medical Examination Adult  #2 Hypertension Essential Primary  #3 Anemia Pernicious  #4 Rhinosinusitis Chronic  #5 Primary Malignant Neoplasm Of Prostate (HCC)      Plan     #1 .  Today he was given Prevnar 20.    #2 .  Stable.  I did order a BMP.      #3 .  Stable.  I did order a CBC and vitamin B12 level.      #4 .  Stable.      #5 .  We had a long discussion regarding his diagnosis.         The following counseling and/or anticipatory guidelines were reviewed with the patient:  diet & nutrition and physical activity      The following counseling and/or anticipatory guidelines were reviewed with the patient:  prescriptions  and supplemental drug interactions        The health maintenance module was reviewed, addressed as agreed upon with the patient, and updated.       Follow up in about 1 year for a yearly evaluation or sooner if needed.

**Comment by joshy** [comment]
Hi, is it possible to get a real rtf with the unmatched curly brace? Please remove patient information. I have tried with your example and on a minimal example but both times it worked. Just inserting a curly brace is not enough. 
Thanks, Joshy

**Comment by crystal-butler** [comment]
Thanks for the response. I'm processing a variety of texts with unknown formatting that go through a series of steps to clean up unwanted symbols and characters, including a run through `rtf_to_text`. Under Python 3.10 and 3.11, with striprtf version 0.0.27, I get truncated text out of `rtf_to_text` using the example I included in this issue. However, if I open the example in MIcrosoft Word and save it out as an RTF file, the text does not get truncated, so it look like this problem could be with my application of striprtf to text that doesn't have correct RTF formatting.
