### ISSUE TITLE
Default Font is not used

### ISSUE THREAD

**Issue by MalkmusT** [joshy/striprtf#56]
I have some encoding problems for rtf documents the have umluate in default font regions

The following pyhton script 
```
#!/bin/env python
# -*- coding: utf-8 -*-


import sys
from striprtf.striprtf import rtf_to_text


test_str='''
{\\rtf1\\ansi\\ansicpg1252\\uc1\\deff0\\stshfdbch0\\stshfloch0\\stshfhich0\\stshfbi0\\deflang1031\\deflangfe1031{ \\fonttbl {\\f0\\froman\\fcharset0\\fprq2{\\*\\panose 02020603050405020304}Times New Roman;} {\\f395\\fswiss\\fcharset222\\fprq2 Tahoma (Thai);} } {\\fs28\\cf1\\insrsid9330230 \\'fc } }
'''

rtf_text = rtf_to_text( test_str )
print( rtf_text )
```
thorws a decoding Exception 
``` 
UnicodeDecodeError: 'charmap' codec can't decode byte 0xfc in position 0: character maps to <undefined>
```

This looks to me as if the current font definition is not reset to default after creating the font table.

**Comment by joshy** [comment]
Hi Tobias
Thanks for the report. It indeed tries to decode ü with the Thai character set and this will fail. I will prepare a fix but in the mean time do you some examples where both Thai and German texts are mixed? I would add it to my test suite. 
Thanks, Joshy

**Comment by MalkmusT** [comment]
Hey @joshy thank you for your reply.

I dont have a mixed document at hand, but i can provide this synthetic test document where both character sets are used:
``` 
test_str='''
{\\rtf1\\ansi\\ansicpg1252\\uc1\\deff0\\stshfdbch0\\stshfloch0\\stshfhich0\\stshfbi0\\deflang1031\\deflangfe1031{ \\fonttbl {\\f0\\froman\\fcharset0\\fprq2{\\*\\panose 02020603050405020304}Times New Roman;} {\\f395\\fswiss\\fcharset222\\fprq2 Tahoma (Thai);} } {\\fs28\\cf1\\insrsid9330230 \\'fc } {\\f395 \\'E0} \\'fc {\\f0  \\'fc} }
'''
 ```

**Comment by joshy** [comment]
Hi Tobias, this should be fixed with https://github.com/joshy/striprtf/releases/tag/v0.0.28.
