### ISSUE TITLE
NoneType error

### ISSUE THREAD

**Issue by janeshrapnel** [joshy/striprtf#6]
I am getting a TypeError in the code and its breaking at at line 116:  c = int(arg)

I am getting the following error:
TypeError: ("int() argument must be a string, a bytes-like object or a number, not 'NoneType'", 'occurred at index 165970')

The code used is below and is used to decompress BLOBs in a database. It works fine when compress is 361 but not 360.

This is the code that is running:
```
def `deblob3(row):`
    if pd.notnull(row[0]):
        blob = row[0]
        h = html2text.HTML2Text()
        h.ignore_links=True
        if type(blob) != bytes:
            blobbytes = blob.read()[:-10]
        else:
            blobbytes = blob[:-10]
        if row[1]==361:            
            return h.handle(striprtf(decompress_without_eoi(blobbytes)))
        elif row[1]==360: 
            return h.handle(striprtf(blobbytes))
```

**Comment by joshy** [comment]
Hi, thanks for the report. Could you maybe provide the string or better the rtf file (the content of *decompress_without_eoi(blobbytes))*?

**Comment by janeshrapnel** [comment]
Thanks Joshy. It is actually the 360 compression that isn't working. I am also aware that it may not be this program that is causing the error, this just happens to be where it is coming up with the error. 

So the file looks like the attached file. I haven't put in the full IS_BLOB but it's a byte format
[Example_File.txt](https://github.com/joshy/striprtf/files/4259106/Example_File.txt)

**Comment by Robabrown** [comment]
Hello I'm getting this exact same error, on line 126 its throwing "argument must be a string type... not "noneType.  Here's the copy of the rtf that's causing the error
cf1\\fs22\\par\\plain\\f1\\fs22\\u*

-- It blows up when it gets to "u"

**Comment by joshy** [comment]
Hi Robabrown, can you sent me the full rtf file? Is \u* even valid?

**Comment by Robabrown** [comment]
here is the complete line of rtf that causes the error:
'r\\plain\\f1\\fs22 - continue home citric acid/sodium citrate, folic acid, B vitamin complex\\plain\\f2\\fs22\\lang1033\\hich\\f2\\dbch\\f2\\loch\\f2\\cf1\\fs22\\par\\plain\\f1\\fs22 - Strict I/Os\\plain\\f2\\fs22\\lang1033\\hich\\f2\\dbch\\f2\\loch\\f2\\cf1\\fs22\\par\\plain\\f1\\fs22\\u*'

**Comment by joshy** [comment]
Hmm, I guess the star in \u* is the problem. This is not covered in the [RTF Spec](http://www.biblioscape.com/rtf15_spec.htm). I will see what I can do to fix it.

**Comment by joshy** [comment]
Fixed with https://github.com/joshy/striprtf/releases/tag/v0.0.9
