### ISSUE TITLE
Installation error: syntax erron in setup.py file

### ISSUE THREAD

**Issue by kappafix** [joshy/striprtf#7]
During the install ov the version "striprtf-0.0.7"using pip or also manually there's a syntax error into setup.py that stops the installation:
the error is at the line:
download_url=f"https://github.com/joshy/striprtf/archive/v{about['__version__']}.tar.gz",
I solved the problem as followings:
download_url=r"https://github.com/joshy/striprtf/archive/v{about['__version__']}.tar.gz",
and installing manually.
Thaks guys, very good library.

**Comment by joshy** [comment]
Hi kappafix, are you using python2? Because f-strings (f"") are only available since 3.6.

**Comment by kappafix** [comment]
Hi, I’m using the 3.4 version.

**Comment by joshy** [comment]
I will fix that in the next version. Don’t want to enforce 3.6. Thanks for the report.

--

**Comment by joshy** [comment]
Fixed with [v0.0.8](https://github.com/joshy/striprtf/releases/tag/v0.0.8)
