### ISSUE TITLE
Extra required library (tabulate) when pip installing v0.0.9 that isn't in setup.py 

### ISSUE THREAD

**Issue by jenojp** [joshy/striprtf#8]
Hi there, great work on this package! - I went to give the new version a try and noticed this issue when doing the following:

```
pip install striprtf==0.0.9
```

and importing the library:

```
from striprtf.striprtf import rtf_to_text
```

I'll get the error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.7/site-packages/striprtf/striprtf.py", line 3, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'
```

Pip grabs from this location: `https://files.pythonhosted.org/packages/3a/0e/b1ee494c9bea3938d56478e2b32c650802e0e73fafa03b4077908922882d/striprtf-0.0.9.tar.gz`

And if I manually unzip, I do see this in line 3
`from tabulate import tabulate`

I should note that if I manually install tabulate, no issue as expected.

**Comment by joshy** [comment]
Shit, somehow messed up the upload to pypi with local changes. Please use https://github.com/joshy/striprtf/releases/tag/v0.0.10. Thanks for issue!
